### PR TITLE
Linux serial ports

### PR DESCRIPTION
**Pull request by amellalalex**
I introduced the linux serial ports folder and included the first working example. There should be enough documentation to outline the purpose of each subdirectory inside. 

The example also includes documentation and source code comments to be used as a resource for anyone looking for a quick and informative stepping stone.

Don't hesitate talking to me about any possible variations in this initial submission.

Thanks!

Alex

### CODE REVIEW

**Comment by liamhebert** [comment]
I’ll produce a more thorough review soon but I’d like to share some of my initial thoughts after a brief review 

- Placeholder return type ints seem a little odd. Ideally, error detection should happen within in the methods themselves. For example, this could be done by catching the return of open() or write() and checking if they indicative of error (I believe they return negative if so, I’ll have to double check) 
- Your slave and master port code seem to be an ideal candidate for objects. I’d recommend looking into converting this code into c++ code to benefit from that structure. Additionally, it would make the code more legible and easier to follow where certain methods are coming from. 
- Lastly, this is pretty unrelated but I’d recommend looking into [cmake](cmake.org) as a build system to allow for easy cross platform integration of this source code. 

Besides that, it looks like a good start! Expect more in-depth comments in a few days

**Comment by liamhebert** [comment]
Oh! You may be interested in using this as a logging system if you do decide to switch to c++, [Spdlog](https://github.com/gabime/spdlog). Super quick, super easy to use and provides lots of cool functionality (like daily rotating text file logging!). I mention this because I’ve noticed you started to log error levels, very cool!

**Comment by amellalalex** [comment]
Awesome, thanks for the ton of feedback! I'll go over each of the points you've suggested and make adjustments accordingly.

**Review by liamhebert — CHANGES_REQUESTED** [review]
This is looking really nice. Just make sure to remove the CMakeFiles folder and any executables from the build tree as they are machine specific binaries and files. Additionally, it would be very clean if you could separate external folders and include files into a `include` directory. Lastly, this is mostly a question, is LibSerial a header only library or is it compiled? I'm curious how you are integrating it into this project. Once these concerns are addressed, I'd be happy merging this :)

**Comment by amellalalex** [comment]
Done! 

LibSerial is a compiled library. The CMakeLists.txt automatically links the library to the binary when compiling the example. I put more information about LibSerial on the readme for the example!

**Review by liamhebert — APPROVED** [review]

**Pull request merged**
